### ISSUE TITLE
Playback.app have .git folder packaged

### ISSUE THREAD

**Issue by deksden** [mafintosh/playback#62]
Just look at Playback.app in Content/Resources/app/.git

IMHO, this folder is not needed in packaged app.

Did not examine build process yet, but maybe some script for packaging can be tuned just to remove this folder.

**Comment by mafintosh** [comment]
Ah yea. We should fix this.

**Comment by seungjulee** [comment]
I just browsed Playback.app/Content/Resources/app/ folder for version 1.6, and it seems like .git folder is no longer there as a result of adding ignore script at package.json. 

Trivial, but I noticed that  .DS_Store file exist in Playback.app/Content/Resources/app/ even though .gitignore specifies .DS_Store. It seems like the file was added to original git repo. 

We should close this issue since this is no longer applies on version 1.6.

[From electron-packager](https://github.com/maxogden/electron-packager)
> Be careful not to include node_modules you don't want into your final app. electron-packager, electron-prebuilt and .git will be ignored by default. You can use --ignore to ignore files and folders via a regular expression. For example, --ignore=node_modules/electron-packager or --ignore="node_modules/(electron-packager|electron-prebuilt)".
